version: "3"

tasks: 
  generateAuth:
    aliases:
      - generate
    desc: "Generate code from proto files"
    cmds:
      - protoc -I proto proto/ggsel/auth.proto --go_out=./gen/go  --go_opt=paths=source_relative --go-grpc_out=./gen/go/ --go-grpc_opt=paths=source_relative
  generateProduct:
    aliases:
      - generate
    desc: "Generate code from proto files"
    cmds:
      - protoc -I proto proto/ggsel/product.proto --go_out=./gen/go  --go_opt=paths=source_relative --go-grpc_out=./gen/go/ --go-grpc_opt=paths=source_relative
  generatePayment:
    aliases:
      - generates
    desc: "Generate code from proto files"
    cmds:
      - protoc -I proto proto/ggsel/payment.proto --go_out=./gen/go  --go_opt=paths=source_relative --go-grpc_out=./gen/go/ --go-grpc_opt=paths=source_relative